from __future__ import absolute_import
from enum import Enum


class NotificationType(unicode, Enum):
    ANY_OFFER_CHANGED = u'ANY_OFFER_CHANGED'
    FEED_PROCESSING_FINISHED = u'FEED_PROCESSING_FINISHED'
    FBA_OUTBOUND_SHIPMENT_STATUS = u'FBA_OUTBOUND_SHIPMENT_STATUS'
    FEE_PROMOTION = u'FEE_PROMOTION'
    FULFILLMENT_ORDER_STATUS = u'FULFILLMENT_ORDER_STATUS'
    REPORT_PROCESSING_FINISHED = u'REPORT_PROCESSING_FINISHED'
    BRANDED_ITEM_CONTENT_CHANGE = u'BRANDED_ITEM_CONTENT_CHANGE'
    ITEM_PRODUCT_TYPE_CHANGE = u'ITEM_PRODUCT_TYPE_CHANGE'
    MFN_ORDER_STATUS_CHANGE = u'MFN_ORDER_STATUS_CHANGE'
    B2B_ANY_OFFER_CHANGED = u'B2B_ANY_OFFER_CHANGED'
